spring:
  ai:
    model:
      embedding: "none"
    ollama:
      base-url: "http://localhost:11434"
      chat:
        model: "qwen3.5:9b"
        temperature: 0.8
        think: false
      init:
        pull-model-strategy: "WHEN_MISSING"
        timeout: "15m"
