---
services:
  ollama:
    image: ollama/ollama:0.12.4
    hostname: ollama
    container_name: ollama
    networks:
      - spring-boot-ai-quickstarts
    ports:
      - "11434:11434"
    restart: unless-stopped

  pgvector:
    image: pgvector/pgvector:pg18
    hostname: pgvector
    container_name: pgvector
    networks:
      - spring-boot-ai-quickstarts
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    restart: unless-stopped

  chat-retrieval-augmented-generation:
    image: loicgreffier/spring-boot-ai-quickstarts:chat-retrieval-augmented-generation-1.0.0
    hostname: chat-retrieval-augmented-generation
    container_name: chat-retrieval-augmented-generation
    networks:
      - spring-boot-ai-quickstarts
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring": {
            "ai": {
              "ollama": {
                "base-url": "http://ollama:11434",
                "chat": {
                  "options": {
                    "model": "gemma3:4b"
                  }
                },
                "embedding": {
                  "options": {
                    "model": "qwen3-embedding:0.6b"
                  }
                }
              }
            }
          }
        }

networks:
  spring-boot-ai-quickstarts:
    driver: bridge
