---
services:
  ollama:
    image: ollama/ollama:0.12.3
    hostname: ollama
    container_name: ollama
    networks:
      - spring-boot-ai-quickstarts
    ports:
      - "11434:11434"
    restart: unless-stopped

  chat-stream:
    image: loicgreffier/spring-boot-ai-quickstarts:chat-stream-1.0.0
    hostname: chat-stream
    container_name: chat-stream
    networks:
      - spring-boot-ai-quickstarts
    depends_on:
      - ollama
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring": {
            "ai": {
              "ollama": {
                "base-url": "http://ollama:11434",
                "chat": {
                  "options": {
                    "model": "gemma3:4b"
                  }
                }
              }
            }
          }
        }

networks:
  spring-boot-ai-quickstarts:
    driver: bridge
